main: com.rodev.etools.Main
name: EnchantedTools
version: 1.0-SNAPSHOT
api-version: 1.13
depend: [BuildUtils, GLib, BuildSkyBlock]
commands:
  enchantedtools:
    description: "Plugin's main command"
    aliases: [et, etools]